version: '3.8'

services:
  # --- SERVICIO DEL BACKEND (NestJS) ---
  backend:
    build:
      context: ./backend # Ruta a la carpeta de tu backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Mapea el puerto 3000 de tu computadora al contenedor
    environment:
      - NODE_ENV=development
      # Aquí puedes poner tus variables de entorno locales de la base de datos
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - essen-network

  # --- SERVICIO DEL FRONTEND (React + Vite) ---
  frontend:
    build:
      context: ./frontend # Ruta a la carpeta de tu frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Puerto por defecto de Vite (o cambia al que uses)
    environment:
      - VITE_API_URL=http://localhost:3000 # Apunta al backend de Docker
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - essen-network
    depends_on:
      - backend # Le dice a Docker que levante primero el backend

networks:
  essen-network:
    driver: bridge