apiVersion: v1
kind: Service
metadata:
  name: his-frontend-service
spec:
  selector:
    app: his-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # En la nube esto te daría una IP pública